# if, elif, else statements


In [3]:
if True:
    print("Yes! It was true")

Yes! It was true


In [7]:
x = False

if x:
    print("Yes! it was true")
else: 
    print("I will be printed in any case where {} is not true" .format('x'))

I will be printed in any case where x is not true


### Mutiple Branches

In [10]:
loc = 'Andhra Pradesh'
if loc == 'Banglore':
    print("Welcome to the Banglore!")
elif loc == 'Andhra Pradesh':
    print("Welcome to the Andhra Pradesh!")
else:
    print("Going somewhere else")

Welcome to the Andhra Pradesh!


# For Loop

In [11]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for num in list1:
    print("{} is {}".format('num', num))

num is 1
num is 2
num is 3
num is 4
num is 5
num is 6
num is 7
num is 8
num is 9
num is 10


In [14]:
for num in list1:
    if num % 2 == 0:
        print("{} is {}".format(num, 'even'))

2 is even
4 is even
6 is even
8 is even
10 is even


In [16]:
for num in list1:
    if num % 2 == 0:
        print(num)
    else:
        print('{} is Odd Number'.format(num))

1 is Odd Number
2
3 is Odd Number
4
5 is Odd Number
6
7 is Odd Number
8
9 is Odd Number
10


In [18]:
list_sum = 0

for num in list1:
    list_sum = list_sum + num

print(list_sum)

55


In [21]:
for i in range(10):
    print("The count is : ", i)

The count is :  0
The count is :  1
The count is :  2
The count is :  3
The count is :  4
The count is :  5
The count is :  6
The count is :  7
The count is :  8
The count is :  9


In [22]:
for i in 'python':
    print('Current Letter : ', i)

Current Letter :  p
Current Letter :  y
Current Letter :  t
Current Letter :  h
Current Letter :  o
Current Letter :  n


In [3]:
fruits = ['banana', 'apple', 'mango']
for fruit in fruits:
    print('Current fruit :', fruit)

Current fruit : banana
Current fruit : apple
Current fruit : mango


In [10]:
for num in range(10, 20):
    for i in range(2, num):
        if num%i == 0:
            j = num/i
            print('%d equals %d * %d' % (num, i, j))
            break
        else:
            print(num, 'is a prime number')
            break

10 equals 2 * 5
11 is a prime number
12 equals 2 * 6
13 is a prime number
14 equals 2 * 7
15 is a prime number
16 equals 2 * 8
17 is a prime number
18 equals 2 * 9
19 is a prime number


# While Loop

In [4]:
count = 0
while(count<9):
    print("The count is : ",count)
    count = count + 1
print("Good Bye!")

The count is :  0
The count is :  1
The count is :  2
The count is :  3
The count is :  4
The count is :  5
The count is :  6
The count is :  7
The count is :  8
Good Bye!


In [13]:
x = 0
while x<10:
    if x < 10:
        print('x is crrently :',x)
        print('x is stille less than 10, adding 1 to it')
        x+=1
print('Done')

x is crrently : 0
x is stille less than 10, adding 1 to it
x is crrently : 1
x is stille less than 10, adding 1 to it
x is crrently : 2
x is stille less than 10, adding 1 to it
x is crrently : 3
x is stille less than 10, adding 1 to it
x is crrently : 4
x is stille less than 10, adding 1 to it
x is crrently : 5
x is stille less than 10, adding 1 to it
x is crrently : 6
x is stille less than 10, adding 1 to it
x is crrently : 7
x is stille less than 10, adding 1 to it
x is crrently : 8
x is stille less than 10, adding 1 to it
x is crrently : 9
x is stille less than 10, adding 1 to it
Done


## Some good examples

In [23]:
lst = [x for x in 'Edunet']
print(lst)

['E', 'd', 'u', 'n', 'e', 't']


In [19]:
for i in 'Edunet':
    print(i)

E
d
u
n
e
t


# Range in Python

for x in range(10):
    print(x)

In [22]:
# Square numbers in range and turn into list
sqr_lst = [x**2 for x in range(0, 11)]
print(sqr_lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [24]:
x = range(1, 9, 2)
for n in x:
    print(n)

1
3
5
7


# Pass Statement

In [2]:
a = 33
b = 200
if b>a:
    pass

# Delete Statement

In [3]:
x = ["Physics", "Chemistry", "Maths"]
del x[0]
print(x)

['Chemistry', 'Maths']


# Return Statement

In [4]:
def fun():
    str = 'Hello World'
    x = 10
    return [str, x];

# Driver code to test above method 
list = fun()
print(list)

['Hello World', 10]


# Import Statement

In [5]:
import math

x = math.sqrt(64)
print(x)

8.0


# Break Statement

In [6]:
i = 1
while i < 9:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


# Continue Statement

In [8]:
i = 0
while i < 10:
    i += 1
    if i == 3:
        continue
    print(i)

1
2
4
5
6
7
8
9
10


# Function

In [12]:
def show(n):         # defining the function
    print("Value is",n)
a = 10

show(a)    # calling the function

Value is 10


In [14]:
def greetings(s):
    print(f"Hello Mr. {s}, Good MOrning!")
    
greetings("Bermunda")

Hello Mr. Bermunda, Good MOrning!


### Local Value

In [16]:
# Example of local variable
def test1():
    a = 10      # Here a is a local variable
    print("Value of a inside function or local variable is :",a)
    
a = 20
test1()
print("Value of a Outside Function :",a)

Value of a inside function or local variable is : 10
Value of a Outside Function : 20


### Global Variable

In [22]:
# Example of global variable

# Global variable as it is outside the scope of function
x = 'awsome'

# Scope starts
def myFunc():
    print("Python is :",x)
#Scope ended

myFunc()

Python is : awsome


### Arguments in Python

In [23]:
# Here a and b arethe parameter

def sum(a, b):
    return a+b

res = sum(10, 20)
print(res)

30


### Arbitrary arguments (*args)

In [27]:
def my_function(*Student):     # It will make the tuple of all the parameters
    print("The brilliant student is",Student[2])
    print(Student)

my_function("Bermunda", "Binod", "Susuwat")

The brilliant student is Pila
('Bermunda', 'Binod', 'Pila')


### Keyword Argument (**Kwargs)

In [34]:
def my_function(**Student):   # It will make the dictionary of parameters as key and arguments as value
    print("The brilliant student is", Student['fname'], Student['lname'])
    print(Student)
    
my_function(fname = "Ravi", lname = "Sharma")

The brilliant student is Ravi Sharma
{'fname': 'Ravi', 'lname': 'Sharma'}


### Lambda Function

A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

In [35]:
x = lambda a: a + 10
print(x(5))

15


In [36]:
x = lambda a, b: a+b
print(x(5, 10))

15


# Libraries

In [37]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


### Making our own library

In [1]:
import mygreetings
mygreetings.greeting("Bremunda")

Hello, Bremunda


In [3]:
import info
info.person1['name']

'Bermunda'

### Platform library

In [9]:
import platform

x = platform.system()
# func = dir(platform)
print(x)
# print(func)

Windows


### To see how many function inside math library using dir function

In [7]:
import math

x = dir(math)
print(x)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


# OOPs

In [13]:
class car:
    def __init__(self, modelname, year):
        self.modelname = modelname
        self.year = year
    def display(self):
        print(self.modelname, self.year)
        
c1 = car('Toyota', 2016)
c1.display()

Toyota 2016


In [21]:
class Person:
    def __init__(mysillyobject, name, age):
        mysillyobject.name = name
        mysillyobject.age = age
        
    def myfunc(obj):
        print("Hello my name is", obj.name)
        
p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


### Single Inheritance

In [23]:
class Parent():
    def first(self):
        print("First Function")
        
class Child(Parent):
    def second(self):
        print("Second function")
        
ob = Child()
ob.first()
ob.second()

First Function
Second function


### Multiple Inheritance

In [24]:
class Parent():
    def func1(self):
        print('Function one')

class Parent1:
    def func2(self):
        print('Function two')
        
class Parent2(Parent, Parent1):
    def func3(self):
        print("Function three")
        
ob = Parent2()
ob.func1()
ob.func2()
ob.func3()

Function one
Function two
Function three


# Exception Handling

In [3]:
def divide(x, y):
    try:
        # Floor division: Gives only fraction
        # Part as Number
        result = x // y
    except ZeroDivisionError:
        print("Sorry! you are dividing by zero")
    else: 
        print("Yeah! Your answer is :", result)
    finally:
        # this block is always executes regardless of exception generation 
        print("This is always executed")
        
divide(3, 2)
divide(3, 0)

Yeah! Your answer is : 1
This is always executed
Sorry! you are dividing by zero
This is always executed


In [4]:
# Example: IndexError
l1 = [1, 2, 3]
l1[3]

IndexError: list index out of range

In [5]:
# Example: ModuleNotFoundError
import notamodule

ModuleNotFoundError: No module named 'notamodule'

# Numpy Module

### Exercie 1: Create an Array

In [6]:
import numpy as np

my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create 0-D Array

In [10]:
import numpy as np
arr = np.array(42)
print(arr)

42


### Create 1-D Array

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Create 2-D Array

In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### Create 3-D Array

In [14]:
import numpy as np
arr1 = np.array([[[2, 17], [45, 78]], [[88, 92], [60, 76]], [[76, 33], [20, 18]]])
print("Create 3-D Array :",arr1, sep='\n')

Create 3-D Array :
[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


# Exercie 2 - Perform I/O with NumPy

### numpy.save()

In [15]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
np.save('outfile', a)

In [16]:
import numpy as np
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


### savetxt()

In [17]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
np.savetxt('out.txt', a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]


In [21]:
# Problem 1: Create a numpy array containing the numbers from 1 to 10
import numpy as np
x = np.array(list(range(1, 11)))

In [22]:
print(x*3)

[ 3  6  9 12 15 18 21 24 27 30]


# Indexing in NumPy

In [29]:
import numpy as np
arr = np.arange(1, 10, 2)
print("Elements of array :",arr)
# inserting in arr1 by giving index position of arr
arr1 = arr[np.array([4, 0, 2, -1, -2])]
print("Indexed elements of array arr :",arr1)

Elements of array : [1 3 5 7 9]
Indexed elements of array arr : [9 1 5 9 7]


### Indexing in 1 dimension

In [32]:
import numpy as np
array1 = np.arange(4)
print("Array arr1 :", array1)
print(array1[0])
print(array1[1])

Array arr1 : [0 1 2 3]
0
1


### Indexing in 2 dimension

In [33]:
import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3, 4)
print("Array arr1 :\n", arr1)
print(arr1[0, 0])
print(arr1[1, 2])

Array arr1 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
6


### Indexing in 3 Dimension

In [34]:
import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(2, 2, 3)
print("Array arr1: \n", arr1)
print("Element", arr1[1, 0, 2])

Array arr1: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element 8


# Problem 2 - Slicing an array

### Slicing 1D NumPy array

In [35]:
import numpy as np
arr = np.arange(6)
print("Array arr :", arr)
print("Sliced element of array :", arr[1:5])

Array arr : [0 1 2 3 4 5]
Sliced element of array : [1 2 3 4]


### Slicing 2D NumPy array

In [38]:
import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3, 4)
print("Array arr1: \n", arr1)
print('\n')
print("Element of 1st row and 1st column upto last column \n", arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Element of !st row and !st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


# NumPy broadcasting 

In [39]:
import numpy as np

# Create a 3x3 matrix
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Add a scalar to array
scalar = 10
result = arr + scalar

print("Original Array :")
print(arr)
print("\nResultant after braodcastinng :")
print(result)

Original Array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Resultant after braodcastinng :
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [53]:
# Problem : Array creating and indexing 

import numpy as np

# Creating a array number containing from 0 to 9
arr = np.arange(10)

# Print the elements at index 3
print(arr[3])

# Print the last element of the array
print(arr[len(arr) - 1])

# Create a 2D array with shape (3, 3) containing consecutive number from 1
arr1 = np.arange(1, 10).reshape(3,3)

# Print element at row 2 and column 1
print(arr1[2, 1])

3
9
8


In [65]:
# Problem : Slicing and broadcasting

import numpy as np

# Array containing the numberfrom 1 to 10
arr = np.arange(1, 11)
print(arr)

# Using slicing extract element from index 2 to 6
arr1 = arr[1:6]
print(arr1)

# Multiply subarray by 2 using broadcating
multip_arr = arr1 * 2
print(multip_arr)

# Create 2D array with shape(4, 3) containing consecutive number fron 1
arr2 = np.arange(1, 13).reshape(3, 4)
print(arr2)

# Print all the elements of last 2 column of last 2 rows 
print(arr2[:2,:2])

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[ 4  6  8 10 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]


# Structured array in NumPy

In [69]:
# Structure array
import numpy as np
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)], dtype=[('name', (np.str_, 10)), ('age', np.int32), ('weight', np.float64)])
print(a)

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [72]:
import numpy as np

# Calling dtype() constructor and filling it with desired tuples
t= np.dtype([('empname', 'U40'),
             ('age', 'u1'),
             ('salary', 'u4'),
             ('designation', 'U30')])

# Creating a structured array using our dtype:
arr = np.array([('Raj Sharma', 28, 70000, 'Python Developer'),
                ('Kanchan Kashyap', 25, 60000, 'Digital Marketer'),
                ('Mukul Sinha', 26, 52500, 'Software Engineer')], dtype = t)

print(arr)

[('Raj Sharma', 28, 70000, 'Python Developer')
 ('Kanchan Kashyap', 25, 60000, 'Digital Marketer')
 ('Mukul Sinha', 26, 52500, 'Software Engineer')]


# Performing Statistical function in NumPy

In [73]:
# Mean
import numpy as np

data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
print("Mean :",mean)

Mean : 30.0


In [75]:
# Median
import numpy as np

data = np.array([10, 20, 30, 40, 50])
median = np.median(data)
print("Median :",median)

Median : 30.0


In [76]:
# Standard Deviation
import numpy as np

data = np.array([10, 20, 30, 40, 50])
std_dev = np.std(data)
print("Standard Deviation :",std_dev)

Standard Deviation : 14.142135623730951


In [77]:
# Variance
import numpy as np

data = np.array([10, 20 ,30 , 40, 50])
variance = np.var(data)
print("Variance :", variance)

Variance : 200.0


In [79]:
# Percentile
import numpy as np

data = np.array([10, 20, 30, 40, 50])
percentile_75 = np.percentile(data, 75)
print("75th Percentile :", percentile_75)

75th Percentile : 40.0


In [80]:
# Minimum
import numpy as np

data = np.array([10, 20, 30, 40, 50])
minimum = np.min(data)

print("Array :", data)
print("Minimum Value :", minimum)

Array : [10 20 30 40 50]
Minimum Value : 10


In [83]:
import numpy as np

matrix = np.array([[10, 5, 8],
                 [15, 7, 12],
                 [20, 25, 18]])

minimum_along_columns = np.amin(matrix, axis=0)
minimum_along_rows = np.amin(matrix, axis=1)
print("Matrix :")
print(matrix)
print("Minimum along colums :", minimum_along_columns)
print("Minimuin along rows :", minimum_along_rows)

Matrix :
[[10  5  8]
 [15  7 12]
 [20 25 18]]
Minimum along colums : [10  5  8]
Minimuin along rows : [ 5  7 18]
